### ISSUE TITLE
파일 실행 중 utf-8 방식으로 한글 디코딩 안되는 에러

### ISSUE THREAD

**Issue by pgw2001** [bum0w0/RPS_Project#12]
SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xb0 in position 0: invalid start byte
저만 그런건지 모르겠는데 다들 실행되나 확인 부탁드립니다

**Comment by bum0w0** [comment]
저도 pull 이후에 작업트리에서 인코딩 깨져서 방법 찾아보고 있습니다.

**Comment by pgw2001** [comment]
![image](https://github.com/user-attachments/assets/be557f8e-3abe-4696-92cf-54ce5b4585b9)
utf-8로 인코딩을 해봤는데 뭔가 안되는거 같아서 저는 한글 써져있는 파일에 다 윗줄에 # -*- coding: cp949 -*-이렇게 추가하니까 되긴 하더라구요

**Comment by pgw2001** [comment]
아 이럴 필요 없었네요 제가 EUC-KR로 인코딩되어있어서 UTF-8로 바꾸니까 되네요 해결됐습니다 감사합니다
